---
title: "MLR H20 Benchmark gbm nnet"
output:
  html_document: default
  html_notebook: default
---


```{r}
require(mlr)
require(ggplot2)
```


#random seed
```{r}
set.seed(1000)
```


#load results
```{r}
load (file="~/shared/results/bmr_rf_nnet")
```

```{r}
bmr
```


#boxplot
```{r}
plotBMRBoxplots(bmr,measure = auc)
plotBMRBoxplots(bmr,measure = mmce)
```


#violin plots
```{r}
plotBMRBoxplots(bmr, measure = auc, style = "violin", pretty.names = TRUE, facet.wrap.ncol = 3) +
  aes(color = learner.id) +
  theme(strip.text.x = element_text(size = 8))


plotBMRBoxplots(bmr, measure = mmce, style = "violin", pretty.names = TRUE, facet.wrap.ncol = 3) +
  aes(color = learner.id) +
  theme(strip.text.x = element_text(size = 8))
```


#auc total
```{r}
bmr$results

```


#rocs
```{r}
df = generateThreshVsPerfData(bmr, measures = list(fpr,tpr,mmce))
plotROCCurves(df)
```




#summary
```{r}
plt=plotBMRSummary(bmr)
plt+ggtitle("Benchmark aggregate Summary")+
  theme(plot.title = element_text(hjust = 0.5))
```
#ranks
```{r}
m = convertBMRToRankMatrix(bmr, mmce)
m


m = convertBMRToRankMatrix(bmr, auc)
m
```




```{r}
plt=plotBMRRanksAsBarChart(bmr, pos = "tile", measure=mmce)
plt+ggtitle("mmce rank")+
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
plt=plotBMRRanksAsBarChart(bmr, pos = "tile", measure=auc)
plt+ggtitle("auc rank")+
  theme(plot.title = element_text(hjust = 0.5))
```
#Hypothesis test
```{r}

friedmanTestBMR(bmr,auc)
friedmanTestBMR(bmr,mmce)


friedmanPostHocTestBMR(bmr,p.value=0.05,auc)
friedmanPostHocTestBMR(bmr,p.value=0.05,mmce)

g = generateCritDifferencesData(bmr, p.value = 0.05, test = "bd",auc,baseline = "classif.h2o.gbm")
plt=plotCritDifferences(g) + coord_cartesian(xlim = c(-1,5), ylim = c(0,2))
plt+ggtitle("critical diferences, test bd, auc")+
  theme(plot.title = element_text(hjust = 0.5))

g = generateCritDifferencesData(bmr, p.value = 0.05, test = "bd",mmce)
plt=plotCritDifferences(g) + coord_cartesian(xlim = c(-1,5), ylim = c(0,2))
plt+ggtitle("critical diferences, test bd, mmce")+
  theme(plot.title = element_text(hjust = 0.5))

```

