---
# load the data from SQL database and save a dataframe

---
  
#libraries
  
require("RPostgreSQL")


#connect database

drv <- dbDriver("PostgreSQL")
# creates a connection to the postgres database
# note that "con" will be used later in each connection to the database
con <- dbConnect(drv, dbname = "mimicsel",
                 host = "192.168.1.106", port = 5432,
                 user = "mimicsel", password = "mimicsel")


# check for the cartable
dbExistsTable(con, "ds_icu_stays_1")
# TRUE


#dataframe from table


ds_icu_pm_1<-dbGetQuery(con,"select 
                        PAT_GENDER,PAT_EXPIRE_HOSP,ADT_HOS_AGE,ADT_HSTAYS,ADT_READMIT,ICU_DBSOURCE,ICU_LOS,ICU_TYPE_FSERVICE,ICU_DEAD_BEFORE_28,ICU_HAS_PRESC_INSULIN,
                        ICU_HAS_ADMIV_INSULIN,ICU_HAS_ADMIT_INSULIN,ICU_STAY_MORE72,ICD9P_M,ICD9D_M,ICD9D_M_CHAPTER,DIAG_M_HAS_DIABET,DIAG_S_HAS_DIABET,COM_CONGEST_HEA_FAILURE ,COM_CARDIAC_ARRHYTHMIAS ,
                        COM_VALVULA_DISEASE ,COM_PULMONA_CIR_DISORDERS ,COM_PERIPHE_VAS_DISORDERS ,COM_HYPERTENSION ,COM_PARALYSIS ,COM_OTHER_NEUR_DISORDERS ,COM_CHRONIC_PUL_DISEASE ,
                        COM_DIABETES_UNCOMPLICATED ,COM_DIABETES_COMPLICATED ,COM_HYPOTHYROIDISM ,COM_RENAL_FAILURE ,COM_LIVER_DISEASE ,COM_PEPTIC_ULC_DISEASE ,COM_AIDS ,
                        COM_LYMPHOMA ,COM_METASTATIC_CANCER ,COM_SOLID_TUM_WO_METASTASIS ,COM_RHEUMATOID_ART_DISEASES ,COM_COAGULOPATHY ,COM_OBESITY ,COM_WEIGHT_LOSS ,COM_FLUID_ELEC_DISORDERS ,
                        COM_BLOOD_LOS_ANEMIA ,COM_DEFICIENCY_ANEMIAS ,COM_ALCOHOL_ABUSE ,COM_DRUG_ABUSE ,COM_PSYCHOSES ,COM_DEPRESSION ,SCORE_APSIII,SCORE_LODS,
                        SCORE_MLODS,SCORE_OASIS,SCORE_QSOFA,SCORE_SAPS,SCORE_SAPSII,SCORE_SOFA,SCORE_SIRS,MED_HAS_ALLERGIE_INSULIN,MED_HAS_INFECTION,MED_HAS_EXPLICIT_SEPSIS,
                        MED_HAS_ORGAN_DYSFUNCTION,MED_HAS_SEPSIS,MED_HAS_VASO,MED_HAS_24H_VASO,MED_HAS_DIALYSIS,MED_HAS_24H_DIALYSIS,MED_HAS_MECHVENT,MED_HAS_24H_MECHVENT,
                        MED_HAS_ESTEROID_PRESC,PH_AVG_24H,PH_STD_24H,PO2_AVG_24H,PO2_STD_24H,WHITEBLOOD_AVG_24H,WHITEBLOOD_STD_24H,LACTATE_AVG_24H,LACTATE_STD_24H,
                        HEMOGLOBIN_AVG_24H,HEMOGLOBIN_STD_24H,PCO2_AVG_24H,PCO2_STD_24H,BICARBONATE_AVG_24H,BICARBONATE_STD_24H,CREATININE_AVG_24H,CREATININE_STD_24H,PH_AVG_48H,
                        PH_STD_48H,PO2_AVG_48H,PO2_STD_48H,WHITEBLOOD_AVG_48H,WHITEBLOOD_STD_48H,LACTATE_AVG_48H,LACTATE_STD_48H,HEMOGLOBIN_AVG_48H,HEMOGLOBIN_STD_48H,PCO2_AVG_48H,
                        PCO2_STD_48H,BICARBONATE_AVG_48H,BICARBONATE_STD_48H,CREATININE_AVG_48H,CREATININE_STD_48H,PH_AVG_72H,PH_STD_72H,PO2_AVG_72H,PO2_STD_72H,WHITEBLOOD_AVG_72H,
                        WHITEBLOOD_STD_72H,LACTATE_AVG_72H,LACTATE_STD_72H,HEMOGLOBIN_AVG_72H,HEMOGLOBIN_STD_72H,PCO2_AVG_72H,PCO2_STD_72H,BICARBONATE_AVG_72H,BICARBONATE_STD_72H,
                        CREATININE_STD_72H,CREATININE_AVG_72H,GLUCOSE_VARIABILITY_ICU,TIME_HIPO_CRITICAL_SUM_24H,TIME_HIPO_MODERATE_SUM_24H,TIME_HYPER_GLUCE_SUM_24H,TIME_RANGE_PROTOCOL_SUM_24H,
                        TIME_RANGE_CLINIC_SUM_24H,GLUCOSE_VARIABILITY_24H,TIME_HIPO_CRITICAL_SUM_48H,TIME_HIPO_MODERATE_SUM_48H,TIME_HYPER_GLUCE_SUM_48H,TIME_RANGE_PROTOCOL_SUM_48H,
                        TIME_RANGE_CLINIC_SUM_48H,GLUCOSE_VARIABILITY_48H,TIME_HIPO_CRITICAL_SUM_72H,TIME_HIPO_MODERATE_SUM_72H,TIME_HYPER_GLUCE_SUM_72H,TIME_RANGE_PROTOCOL_SUM_72H,
                        TIME_RANGE_CLINIC_SUM_72H,
                        HIPO_CRITICAL_PERCENT_ICU,HIPO_MODERATE_PERCENT_ICU,HYPER_GLUCE_PERCENT_ICU,IN_RANGE_CLINIC_PERCENT_ICU,IN_RANGE_PROTOCOL_PERCENT_ICU,
                        HIPO_CRITICAL_PERCENT_24H,HIPO_MODERATE_PERCENT_24H,HYPER_GLUCE_PERCENT_24H,IN_RANGE_CLINIC_PERCENT_24H,IN_RANGE_PROTOCOL_PERCENT_24H,
                        HIPO_CRITICAL_PERCENT_48H,HIPO_MODERATE_PERCENT_48H,HYPER_GLUCE_PERCENT_48H,IN_RANGE_CLINIC_PERCENT_48H,IN_RANGE_PROTOCOL_PERCENT_48H,
                        HIPO_CRITICAL_PERCENT_72H,HIPO_MODERATE_PERCENT_72H,HYPER_GLUCE_PERCENT_72H,IN_RANGE_CLINIC_PERCENT_72H,IN_RANGE_PROTOCOL_PERCENT_72H,
                        GLUCOSE_VARIABILITY_72H,NUT_TPN_IN_24H,NUT_NPO_IN_24H,NUT_PPN_IN_24H,
                        NUT_TFE_IN_24H,NUT_TPN_IN_48H,NUT_NPO_IN_48H,NUT_PPN_IN_48H,NUT_TFE_IN_48H,NUT_TPN_IN_72H,NUT_NPO_IN_72H,NUT_PPN_IN_72H,NUT_TFE_IN_72H
                        from 
                        ds_icu_stays_1")


save(file="~/shared/ds_icu_raw_1",ds_icu_pm_1)

