

```{r}

require(h2o)
require(caret)
require(pROC)
require(dplyr)

#random seed

set.seed(1000)

#start h2o

h2o.init(nthreads=-1, max_mem_size = "7G")
#h2o.removeAll()
#h2o.shutdown(prompt = FALSE)

# LOAD DATASET
load("~/shared/datasets/ds_icu_pm_complete__no_fact_2")
#load("~/shared/datasets/ds_icu_pm_complete_2")
#load("~/shared/datasets/ds_icu_pm_only_glucose_2")


#variables
y<-"icu_dead_before_28"

```


#dataset total
```{r}

lmdl<-list()

train<-createDataPartition(y=ds_icu_pm_2$icu_dead_before_28,p=.60,list = FALSE)
d_train<-ds_icu_pm_2[train,]
d_test<-ds_icu_pm_2[-train,]
  


#glm full 
time_train<-system.time(glm_iter <- h2o.glm(y = y,
                                              training_frame = as.h2o(d_train),
                                              validation_frame = as.h2o(d_test),
                                              family = "binomial",
                                              link="logit",
                                              balance_classes = TRUE,
                                              lambda = 0,
                                              standardize=TRUE,
                                              remove_collinear_columns=TRUE,
                                              compute_p_values=TRUE,
                                              nfolds = 10,
                                              keep_cross_validation_predictions = TRUE,
                                              keep_cross_validation_fold_assignment = TRUE,
                                              seed = 1)
                                              )
lmdl<-glm_iter

save(lmdl,file="~/shared/results/lmdl_201809_01_total_no_fact")

```

```{r}
summary(lmdl)
```


```{r}

#AUC
tauc<-paste(format(lmdl@model$training_metrics@metrics$AUC,digits=3),"Train")
vauc<-paste(format(lmdl@model$validation_metrics@metrics$AUC,digits=3),"Validation")
cvauc<-paste(format(lmdl@model$cross_validation_metrics@metrics$AUC,digits=3),"Cross Val")


lmdl@model$training_metrics@metrics$AUC
lmdl@model$validation_metrics@metrics$AUC
lmdl@model$cross_validation_metrics@metrics$AUC




```

#coeficients
```{r}
h2o.coef(lmdl)
```

#normalized coeficients
```{r}
h2o.coef_norm(lmdl)
```

#coeficients table
```{r}
View(lmdl@model$coefficients_table)
```


#variable importance
```{r}
h2o.std_coef_plot(lmdl,50)
```


#ROC curve
#TODO buscar una mejor o ver como formatearla con ggplot
```{r}
fpr = lmdl@model$training_metrics@metrics$thresholds_and_metric_scores$fpr
tpr = lmdl@model$training_metrics@metrics$thresholds_and_metric_scores$tpr
fpr_val = lmdl@model$validation_metrics@metrics$thresholds_and_metric_scores$fpr
tpr_val = lmdl@model$validation_metrics@metrics$thresholds_and_metric_scores$tpr
fpr_cv = lmdl@model$cross_validation_metrics@metrics$thresholds_and_metric_scores$fpr
tpr_cv = lmdl@model$cross_validation_metrics@metrics$thresholds_and_metric_scores$tpr
plot(fpr,tpr, type='l')
title('AUC')
lines(fpr_val,tpr_val,type='l',col='green')
lines(fpr_cv,tpr_cv,type='l',col='red')
legend("bottomright",c(tauc,vauc,cvauc),col=c("black","green","red"),lty=c(1,1),lwd=c(3,3))

```


  
```{r}
h2o.auc(lmdl,valid=FALSE) # on train
h2o.auc(lmdl,valid=TRUE) # on test
```
#confusion matrix
```{r}
lmdl@model$training_metrics@metrics$max_criteria_and_metric_scores

```

